---
# 🧩 Playbook: inst-zsh.yaml
# 📘 Description:
# Installs the Z Shell (zsh) package on selected Ubuntu/Debian-based hosts.
#
# 🔧 Notes:
# - Targets hosts specified via the `target_group` variable.
# - Requires sudo privileges.
# - Compatible with Debian/Ubuntu systems using `apt`.
#
# 🧠 Example usage:
# ansible-playbook -i inventory.ini ./ubuntu/inst-zsh.yaml -e "target_group=UbuntuServers"

- name: Install zsh
  hosts: "{{ target_group | d([]) }}"
  become: true
  gather_facts: true

  tasks:
    - name: Install zsh
      ansible.builtin.apt:
        name: zsh
        state: present
        update_cache: true
      become: true
