---
- name: Check if system reboot is required
  hosts: "{{ target_group | d('all') }}"
  become: true
  gather_facts: no

  vars:
    telegram_bot_token: "{{ lookup('env', 'TELEGRAM_BOT_TOKEN') }}"
    telegram_chat_id: "{{ lookup('env', 'TELEGRAM_CHAT_ID') }}"

  tasks:
    - name: Check if system reboot is required
      ansible.builtin.stat:
        path: /run/reboot-required
      register: reboot_required

    - name: Report in logs if reboot is required
      ansible.builtin.debug:
        msg: "Reboot is required on {{ inventory_hostname }}"
      when: reboot_required.stat.exists

    - name: Send Telegram alert if reboot is required
      ansible.builtin.uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "⚠️ *Reboot Required:* Host `{{ inventory_hostname }}` needs a reboot."
          parse_mode: "Markdown"
        status_code: 200
      when: reboot_required.stat.exists
