---
# 🧩 Playbook: upd-upgrade-apt.yaml
# 📘 Description:
# Updates and upgrades all packages on Debian/Ubuntu-based systems using the `apt` package manager.
# The playbook refreshes the package cache and performs a full system upgrade (dist-upgrade),
# ensuring that all dependencies and kernel updates are applied.
#
# 🔧 Notes:
# - Designed for Debian and Ubuntu hosts (checks if the package manager is `apt`).
# - Can be safely applied to all hosts that use apt without modifying non-apt systems.
# - Requires privilege escalation (sudo/root) to execute package management tasks.
# - Consider pairing this with the `check_reboot_required.yml` playbook to verify
#   if a reboot is needed after the upgrade.
#
# 🧠 Example usage:
# ansible-playbook -i inventory.ini ./ubuntu/upd-upgrade-apt.yaml -e "target_group=UbuntuServers"

- name: Update and upgrade apt packages
  hosts: "{{ target_group | d('all') }}"

  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      ansible.builtin.apt:
        upgrade: dist
