---
- name: Update and check OpenWrt router (no Python required)
  hosts: openwrt
  gather_facts: no
  become: yes

  tasks:
    - name: Update package lists
      ansible.builtin.raw: opkg update
      register: update_result

    - name: List upgradable packages
      ansible.builtin.raw: opkg list-upgradable
      register: upgradable

    - name: Show upgradable packages
      ansible.builtin.debug:
        msg: "{{ upgradable.stdout_lines | default(['No packages need upgrading.']) }}"

    - name: Upgrade all packages if needed
      ansible.builtin.raw: opkg upgrade
      when: upgradable.stdout is defined and upgradable.stdout != ""
      register: upgrade_result

    - name: Check if reboot is required (based on kernel or libc upgrade)
      ansible.builtin.set_fact:
        reboot_needed: "{{ 'libc' in upgradable.stdout or 'kernel' in upgradable.stdout }}"
      when: upgradable.stdout is defined

    - name: Reboot if needed
      ansible.builtin.raw: sleep 2 && reboot
      when: reboot_needed | default(false)
      async: 0
      poll: 0

    - name: Wait for router to come back
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 15
        timeout: 180
      when: reboot_needed | default(false)
