---
- name: Update and check OpenWrt router
  hosts: openwrt
  become: yes
  gather_facts: no

  tasks:

    - name: Update package lists
      ansible.builtin.command: opkg update
      register: update_result
      changed_when: "'downloaded' in update_result.stdout"

    - name: List upgradable packages
      ansible.builtin.command: opkg list-upgradable
      register: upgradable
      changed_when: upgradable.stdout != ""

    - name: Show upgradable packages
      debug:
        msg: "{{ upgradable.stdout_lines | default(['No packages need upgrading.']) }}"

    - name: Upgrade all packages
      ansible.builtin.command: opkg upgrade
      when: upgradable.stdout != ""
      register: upgrade_result
      changed_when: "'upgraded' in upgrade_result.stdout or 'Configuring' in upgrade_result.stdout"

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /tmp/reboot-required
      register: reboot_flag

    - name: Reboot if needed
      ansible.builtin.reboot:
        msg: "Rebooting after OpenWrt update"
        pre_reboot_delay: 3
        post_reboot_delay: 15
      when: reboot_flag.stat.exists
