---
- name: Update and check OpenWrt router safely
  hosts: openwrt
  gather_facts: no
  become: yes

  tasks:
    - name: Update package lists
      ansible.builtin.raw: opkg update
      register: update_result

    - name: Get list of upgradable packages
      ansible.builtin.raw: opkg list-upgradable | cut -d ' ' -f1
      register: upgradable

    - name: Show upgradable packages
      ansible.builtin.debug:
        msg: "{{ upgradable.stdout_lines | default(['No packages need upgrading.']) }}"

    - name: Upgrade all upgradable packages (if any)
      ansible.builtin.raw: opkg upgrade {{ upgradable.stdout_lines | join(' ') }}
      when: upgradable.stdout is defined and upgradable.stdout != ""
      register: upgrade_result

    - name: Check if a reboot is likely needed (kernel/libc updated)
      ansible.builtin.set_fact:
        reboot_needed: "{{ 'libc' in upgradable.stdout or 'kernel' in upgradable.stdout }}"
      when: upgradable.stdout is defined

    - name: Reboot router if needed
      ansible.builtin.raw: sleep 3 && reboot
      when: reboot_needed | default(false)
      async: 0
      poll: 0

    - name: Wait for router to come back
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 20
        timeout: 300
      when: reboot_needed | default(false)
