---
# 🧩 Playbook: maint-reboot-required.yaml
# 📘 Description:
# Checks if any target hosts require a system reboot (based on the presence of /run/reboot-required)
# and sends a Telegram notification if a reboot is needed. This is commonly used after
# package upgrades or kernel updates on Ubuntu/Debian systems.
#
# 🔧 Notes:
# - Works on systems that create the `/run/reboot-required` file (Ubuntu/Debian).
# - Requires privilege escalation (sudo/root).
# - Telegram credentials (TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID) should be set
#   as environment variables or stored securely in Semaphore secrets.
# - Uses the Telegram Bot API to deliver alerts directly to your chat.
# - You can modify the message or notification channel as needed.
#
# 🧠 Example usage:
# ansible-playbook -i inventory.ini ./common/maint-reboot-required.yaml -e "target_group=UbuntuServers"

- name: Check if system reboot is required
  hosts: "{{ target_group | d('all') }}"
  become: true
  gather_facts: no

  vars:
    telegram_bot_token: "{{ lookup('env', 'TELEGRAM_BOT_TOKEN') }}"
    telegram_chat_id: "{{ lookup('env', 'TELEGRAM_CHAT_ID') }}"

  tasks:
    - name: Check if system reboot is required
      ansible.builtin.stat:
        path: /run/reboot-required
      register: reboot_required

    - name: Report in logs if reboot is required
      ansible.builtin.debug:
        msg: "Reboot is required on {{ inventory_hostname }}"
      when: reboot_required.stat.exists

    - name: Send Telegram alert if reboot is required
      ansible.builtin.uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "⚠️ *Reboot Required:* Host `{{ inventory_hostname }}` needs a reboot."
          parse_mode: "Markdown"
        status_code: 200
      when: reboot_required.stat.exists
